spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cities
    username: postgres_user_city
    password: super_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true